tools/lint-hunks.py: add text=True to more Subprocess calls
fixes:
  File "tools/lint-hunks.py", line 128, in main
    for line in lint_out.split("\n"):
TypeError: a bytes-like object is required, not 'str'

these were missed in:
9097dcf4f tools/*.py: update to python3

Bug: b/229626362
Change-Id: Ia66de5dfbf4b76ffaf89cf58e4cd438cd8181eec