ratectrl_qmode_test: fix use of uniform_int_distribution
behavior is only defined for short->unsigned long long, not uint8_t:

https://en.cppreference.com/w/cpp/numeric/random/uniform_int_distribution
IntType	-	The result type generated by the generator. The effect
is undefined if this is not one of short, int, long, long long, unsigned
short, unsigned int, unsigned long, or unsigned long long.

this fixes a build error under Visual Studio:
random(2401): error C2338: invalid template argument for
uniform_int_distribution: N4659 29.6.1.1 [rand.req.genl]/1e requires one
of short, int, long, long long, unsigned short, unsigned int, unsigned
long, or unsigned long long

Change-Id: I7a8119bc9b9ac65ca80d31c8c15bc478b2e15845